#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo ${DIR}
CLASSPATH=${DIR}/javagp.jar:${DIR}/lib/jason.jar:${DIR}/lib/pddl4j.jar
java -classpath "${CLASSPATH}" -jar "${DIR}/javagp.jar" $@